### ISSUE TITLE
Remove texts from Text Overview

### ISSUE THREAD

**Issue by mrweiler** [Mirobit/Labelit#11]
Please include a feature to remove texts (that have been imported) from the text overview or the database, respectively.

**Comment by Mirobit** [comment]
This could be a useful feature. I just struggling to find a good position to place to delete button.
I think it should be in text page, since the user probably will check the text before deleting it. Having a delete button next to each text on the project page, is visually too disruptive.

**Comment by mrweiler** [comment]
You could also choose a design analogous to the import function. Put a delete icon next to the import and check buttons which could e.g. add check boxes next to the files as well as a delete button.

**Comment by Mirobit** [comment]
Thank is a good idea. Delete texts is no implemented: 81a5a29d0616a58ec57f43d815d0397dbe9e14d5
For now you can only delete a single text, but it is very easy and fast to delete a few texts in a row.
