### ISSUE TITLE
Add warning for missing keyboard shortcut

### ISSUE THREAD

**Issue by mrweiler** [Mirobit/Labelit#3]
When adding a new category for anonymization without specifying a keyboard shortcut the following warning is presented: "Unexpected server error. Couldn't finish action."
Please add a more specific warning message or make the keyboard shortcut field mandatory.

**Comment by mrweiler** [comment]
This also applies to missing "Name of category" and "Choose category color" fields.

**Comment by mrweiler** [comment]
Also, when using the same keyboard shortcut for two categories the following warning message is shown: "Duplicate category". This should be "Duplicate keyboard shortcut".

**Comment by mrweiler** [comment]
This also applies when using the same color for two different categories.

**Comment by Mirobit** [comment]
That is true. The error messages could be more specific. I will add some more.

**Comment by Mirobit** [comment]
3dc46c613a28d3e93309fbc43b3aefd9395ff1f9 adds more specific error messages and removes the requirement that the color is unique.
