### ISSUE TITLE
Project description is required

### ISSUE THREAD

**Issue by mrweiler** [Mirobit/Labelit#4]
When creating a new project, the project description field is required although it is marked as optional. An error message is shown: "Unexpected server error. Couldn't finish action." 

error.log:
`{"level":30,"time":1588860368251,"pid":2442,"hostname":"XXX","errors":{"description":{"message":"Path `description` is required.","name":"ValidatorError","properties":{"message":"Path `description` is required.","type":"required","path":"description","value":""},"kind":"required","path":"description","value":""}},"_message":"Project validation failed","message":"Project validation failed: description: Path `description` is required.","name":"ValidationError","stack":"ValidationError: Project validation failed: description: Path `description` is required.\n    at new ValidationError (XXX/Labelit/node_modules/mongoose/lib/error/validation.js:31:11)\n    at model.Document.invalidate (XXX/Labelit/node_modules/mongoose/lib/document.js:2557:32)\n    at XXX/Labelit/node_modules/mongoose/lib/document.js:2379:17\n    at XXX/Labelit/node_modules/mongoose/lib/schematype.js:1173:9\n    at processTicksAndRejections (internal/process/task_queues.js:79:11)","type":"Error","msg":"Project validation failed: description: Path `description` is required."}
`

**Comment by Mirobit** [comment]
Thanks for reporting this. ffe5a3bbbc24274210940f16b5530b1b0ba41c6a should fix this.
